# Generated by Django 3.0.9 on 2021-03-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile_num', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('beds_qty', models.IntegerField(default=0)),
                ('baths_qty', models.IntegerField(default=0)),
                ('sqrft', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=500)),
                ('property_id', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('AC', models.BooleanField(default=False)),
                ('builtin_wardrobe', models.BooleanField(default=False)),
                ('dish_washer', models.BooleanField(default=False)),
                ('floor_covering', models.BooleanField(default=False)),
                ('medical', models.BooleanField(default=False)),
                ('fencing', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserRegistration')),
            ],
        ),
    ]
