# Generated by Django 3.0.9 on 2021-03-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210306_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
