# Generated by Django 3.0.9 on 2021-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210308_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
