# Generated by Django 2.2.12 on 2021-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_ownerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
