# Generated by Django 2.2.12 on 2021-03-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.OwnerDetails'),
        ),
    ]
