# Generated by Django 2.2.12 on 2021-03-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210325_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerdetails',
            old_name='username',
            new_name='Owneremail',
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='Ownername',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='Ownerphone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='Ownerstate',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
