# Generated by Django 2.2.12 on 2021-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210330_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
