# Generated by Django 2.2.12 on 2021-04-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='Amount',
            field=models.CharField(choices=[('1000', '1000'), ('2000', '2000')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='Plan',
            field=models.CharField(choices=[('GoldenPlan', 'GoldenPlan'), ('PlatiniumPlan', 'PlatiniumPlan')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
