# Generated by Django 2.2.12 on 2021-04-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210404_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='Amount',
            field=models.IntegerField(default=1),
        ),
    ]
