# Generated by Django 2.2.12 on 2021-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210404_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='Plan',
            field=models.BooleanField(),
        ),
    ]
