# Generated by Django 2.2.12 on 2021-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210404_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
