# Generated by Django 3.1.7 on 2021-04-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_ownerdetails_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProperFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
                ('feedback', models.TextField()),
                ('feed_pos', models.FloatField(default=0.0)),
                ('feed_neg', models.FloatField(default=0.0)),
                ('Product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.listingmodel')),
                ('cust_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.userregistration')),
            ],
        ),
    ]
