# Generated by Django 3.1.7 on 2021-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_properfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='email_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
