# Generated by Django 4.0.2 on 2022-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210428_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='video',
            field=models.FileField(default='', upload_to='video/'),
        ),
    ]
