# Generated by Django 4.0.2 on 2022-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_listingmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='video',
            field=models.FileField(default='', null=True, upload_to='video/'),
        ),
    ]
