# Generated by Django 4.0.2 on 2022-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_listingmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='properfeedback',
            name='feed_polarity',
            field=models.FloatField(default=0.0),
        ),
    ]
