# Generated by Django 4.0.2 on 2022-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_properfeedback_feed_polarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properfeedback',
            old_name='Product_name',
            new_name='Property_name',
        ),
        migrations.AlterField(
            model_name='properfeedback',
            name='feed_polarity',
            field=models.FloatField(default=''),
        ),
    ]
