# Generated by Django 4.0.2 on 2022-03-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_rename_product_name_properfeedback_property_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdetails',
            name='Plan',
        ),
    ]
