# Generated by Django 4.0.2 on 2022-03-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_ownerdetails_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properfeedback',
            name='feed_polarity',
        ),
    ]
