# Generated by Django 3.0 on 2022-04-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_properfeedback_feed_polarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='apartment_type',
            new_name='product_type',
        ),
    ]
