# Generated by Django 3.0 on 2022-04-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20220405_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='product_type',
            new_name='city_type',
        ),
    ]
